 # Defines which nodes are used in the system and how to connect to them.
# This element should only be referenced during the constructor's initial
# setup.
# All names must be unique.
# No other nodes are known.
# These names will be used for src and dest addresses for the Message
# The local node’s name is included in this list
configuration :
  - name : Server1
    ip   : 128.237.215.90
    port : 9001
  - name : Server2
    ip   : 128.237.190.230
    port : 9002
  - name : Server3
    ip   : 128.237.190.230
    port : 9003
  - name : Server4
    ip   : 128.237.190.230
    port : 9004
  - name : Server5
    ip   : 128.237.190.230
    port : 9005   
# group :
#   - name : Group 1
#     members :
#       - bob
#       - Elen 
#       - daphnie
#   - name : Group 2
#     members : 
#       - Francis
#       - bob
#       - Greg
# sendRules : 
#   - action : duplicate 
#     kind : duplicate
# receiveRules :
#   - action : drop 
#     kind   : drop1
#   - action : delay 
#     kind : delay1
#   - action : duplicate 
#     kind : duplicate1